"""
generate_tax_records()
    Tax Status
        Property tax clearance
        Corporate tax compliance records
        Outstanding tax obligations

    Environmental and Business Clearances
        Environmental Impact Assessment (EIA) approvals
        Business licenses
        Other regulatory approvals

"""

import random
import json
from .property import properties

# genarate tax records for properties from the property records generated by generate_properties() function in property.py
