# Generated by Django 6.0.7 on 2026-07-18 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('applicantId', models.AutoField(primary_key=True, serialize=False)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('applicant_name', models.CharField(max_length=250)),
                ('applicant_email', models.EmailField(max_length=150)),
                ('applicant_phone', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['applicant_name'],
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('professionalId', models.AutoField(primary_key=True, serialize=False)),
                ('professional_name', models.CharField(max_length=250)),
                ('professional_type', models.CharField(choices=[('architect', 'Architect'), ('engineer', 'Engineer'), ('surveyor', 'Surveyor')], max_length=50)),
                ('license_number', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['professional_name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectId', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('building_purpose', models.CharField(max_length=250)),
                ('building_height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gross_floor_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_floors', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('upi', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('physical_address', models.CharField(max_length=255)),
                ('property_province', models.CharField(max_length=50)),
                ('property_district', models.CharField(db_index=True, max_length=50)),
                ('property_sector', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'ordering': ['property_province', 'property_district', 'property_sector'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleId', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(choices=[('Chief_Ombudsman', 'Chief Ombudsman'), ('Deputy_Ombudsman', 'Deputy Ombudsman'), ('Monitoring_Officer', 'Monitoring Officer')], default='Monitoring_Officer', max_length=50, unique=True)),
                ('role_description', models.TextField()),
                ('permissions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['role_name'],
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('supervisorId', models.AutoField(primary_key=True, serialize=False)),
                ('supervisor_name', models.CharField(max_length=100)),
                ('supervisor_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('supervisor_phone', models.CharField(max_length=20, unique=True)),
                ('district', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['district'],
            },
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('permitId', models.AutoField(primary_key=True, serialize=False)),
                ('external_permit_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='data_manipulation.applicant')),
                ('architect', models.ForeignKey(blank=True, limit_choices_to={'professional_type': 'architect'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='architect_permits', to='data_manipulation.professional')),
                ('engineer', models.ForeignKey(blank=True, limit_choices_to={'professional_type': 'engineer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineer_permits', to='data_manipulation.professional')),
                ('surveyor', models.ForeignKey(blank=True, limit_choices_to={'professional_type': 'surveyor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveyor_permits', to='data_manipulation.professional')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='data_manipulation.project')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_permits', to='data_manipulation.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_construction_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('contingency_10_percent', models.DecimalField(decimal_places=2, max_digits=20)),
                ('design_fee', models.DecimalField(decimal_places=2, max_digits=20)),
                ('inspection_fee', models.DecimalField(decimal_places=2, max_digits=20)),
                ('permit_fee', models.DecimalField(decimal_places=2, max_digits=20)),
                ('survey_fee', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_estimated_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='RWF', max_length=10)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_data', to='data_manipulation.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='data_manipulation.property'),
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField()),
                ('response_date', models.DateField(blank=True, null=True)),
                ('resubmission_date', models.DateField(blank=True, null=True)),
                ('permit_issuance_date', models.DateField(blank=True, null=True)),
                ('permit_expiration_date', models.DateField(blank=True, null=True)),
                ('review_duration', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Under review', 'Under review')], default='Under review', max_length=20)),
                ('permit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='data_manipulation.permit')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=250)),
                ('user_email', models.EmailField(max_length=150, unique=True)),
                ('user_phone', models.CharField(max_length=15, unique=True)),
                ('user_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='data_manipulation.role')),
            ],
            options={
                'ordering': ['user_name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alertId', models.AutoField(primary_key=True, serialize=False)),
                ('alert_severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=50)),
                ('alert_message', models.TextField()),
                ('alert_timestamp', models.DateTimeField(auto_now_add=True)),
                ('alert_status', models.CharField(choices=[('pending', 'Pending'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=50)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='data_manipulation.permit')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='data_manipulation.project')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='data_manipulation.supervisor')),
                ('monitoring_officer', models.ForeignKey(blank=True, limit_choices_to={'user_role__role_name': 'Monitoring_Officer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='data_manipulation.user')),
            ],
            options={
                'ordering': ['-alert_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Zoning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environmental_protection_boundaries', models.CharField(choices=[('none', 'None'), ('wetland', 'Wetland'), ('river buffer zone', 'River buffer zone'), ('forest reserve', 'Forest reserve'), ('protected area', 'Protected area')], default='none', max_length=200)),
                ('land_use_zoning', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('mixed-use', 'Mixed-use'), ('agricultural', 'Agricultural'), ('institutional', 'Institutional')], max_length=200)),
                ('permitted_building_rights', models.CharField(max_length=200)),
                ('urban_planning_restrictions', models.CharField(choices=[('none', 'None'), ('height restriction', 'Height restriction'), ('road reserve', 'Road reserve'), ('heritage zone', 'Heritage zone'), ('airport corridor', 'Airport corridor'), ('flood-risk area', 'Flood-risk area')], default='none', max_length=200)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zoning', to='data_manipulation.property')),
            ],
        ),
    ]
