# Generated by Django 6.0.7 on 2026-07-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manipulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
