# Generated by Django 4.2.24 on 2026-07-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manipulation', '0002_alertcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('Chief_Ombudsman', 'Chief Ombudsman'), ('Deputy_Ombudsman', 'Deputy Ombudsman'), ('Monitoring_Officer', 'Monitoring Officer'), ('Admin', 'Admin')], default='Monitoring_Officer', max_length=50, unique=True),
        ),
    ]
