# Generated by Django 4.2.24 on 2026-08-02 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manipulation', '0003_alter_role_role_name'),
        ('data_manipulation', '0003_seedroles'),
    ]

    operations = [
    ]
